[build]
  command = "npm install --production && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.x"
  NODE_ENV = "production"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = ["node_modules", ".cache", "build"]