# Railway Deployment Configuration
# Simplified configuration for Railway deployment

[build]
  builder = "dockerfile"

[deploy]
  healthcheckPath = "/health"

[env]
  # These will be set in Railway dashboard
  # DATABASE_URL (automatically provided by Railway PostgreSQL)
  # PORT (automatically set to 8001)
  # LOG_LEVEL = "INFO"
